spring.application.name=travel-managment

# H2 Database
spring.datasource.url=jdbc:h2:file:./data/traveldb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

# JWT
jwt.secret=fawry-travel-planner-super-secret-key-that-is-at-least-32-chars
jwt.expiration=86400000
